# Generated by Django 5.1.3 on 2024-12-03 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LSMSpada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_lsm_spada', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('Pengajar', 'Pengajar'), ('Peserta Didik', 'Peserta Didik')], default='Peserta Didik', max_length=20)),
                ('waktu_akses', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Modul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_modul', models.CharField(max_length=100, unique=True)),
                ('judul_modul', models.CharField(max_length=100)),
                ('jenis_file', models.CharField(max_length=50)),
                ('ukuran_file', models.FloatField(help_text='Ukuran file dalam MB')),
            ],
        ),
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pengguna', models.CharField(max_length=20, unique=True)),
                ('foto_profil', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('nama', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PesertaDidik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_peserta_didik', models.CharField(max_length=20, unique=True)),
                ('status_pendaftaran', models.CharField(max_length=20)),
                ('tanggal_pendaftaran', models.DateField()),
                ('id_pengguna', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='peserta_didik', to='lms.pengguna')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_quiz', models.CharField(max_length=100, unique=True)),
                ('jumlah_soal', models.IntegerField()),
                ('durasi_waktu', models.DurationField()),
                ('tanggal_pengumpulan', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tugas', models.CharField(max_length=100, unique=True)),
                ('nilai_tugas', models.IntegerField()),
                ('tanggal_pengumpulan', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='peserta_didik',
        ),
        migrations.RenameField(
            model_name='pengajar',
            old_name='nidn',
            new_name='status_pengajar',
        ),
        migrations.RemoveField(
            model_name='pengajar',
            name='namaPengajar',
        ),
        migrations.AddField(
            model_name='course',
            name='id_pengajar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='lms.pengajar'),
        ),
        migrations.AddField(
            model_name='pengajar',
            name='id_pengajar',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengajar',
            name='tahun_ajaran',
            field=models.CharField(default='2024/2025', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='id_course',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='modul',
            name='id_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modul', to='lms.course'),
        ),
        migrations.AddField(
            model_name='lsmspada',
            name='id_pengguna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lsm_spada', to='lms.pengguna'),
        ),
        migrations.AddField(
            model_name='pengajar',
            name='id_pengguna',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pengajar', to='lms.pengguna'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='id_peserta_didik',
            field=models.ManyToManyField(related_name='courses', to='lms.pesertadidik'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='id_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='lms.course'),
        ),
        migrations.AddField(
            model_name='tugas',
            name='id_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tugas', to='lms.course'),
        ),
    ]
