# Generated by Django 5.1.3 on 2024-12-03 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_lsmspada_modul_pengguna_pesertadidik_quiz_tugas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id_pengajar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='lms.pengajar'),
        ),
        migrations.CreateModel(
            name='LMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_lms', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('Pengajar', 'Pengajar'), ('Peserta Didik', 'Peserta Didik')], default='Peserta Didik', max_length=20)),
                ('waktu_akses', models.DateTimeField()),
                ('id_pengguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lms', to='lms.pengguna')),
            ],
        ),
        migrations.DeleteModel(
            name='LSMSpada',
        ),
    ]
